version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "monthly"

  # Maintain dependencies for node package manager
  - package-ecosystem: npm
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "monthly"
